### ISSUE TITLE
Set a minApiVersion on a widget-by-widget basis

### ISSUE THREAD

**Issue by KatieZeldaKat** [KatieZeldaKat/openrct2-statistics#7]
As more features get added to the plugin API, more statistics may be added to take advantage of the increased data. However, this also poses the risk of people still using older versions which cannot track these statistics. As it stands, there is no check to ensure players are using a compatible version of the plugin API.

There exists a `minApiVersion` when registering a plugin, but for the purposes of this project, this is not a good fit. Say, a player wishes to track time spent in parks. However, they are using the previous version of the plugin API after we updated to track a brand new statistic. Well, the player doesn't need to track that new statistic, but we are locking them out despite time tracking still having support.

---

The proposed solution is to make a new class: `UnsupportedStatistic`. It will extend `Statistic` so it may be returned in its place when being added to the `StatController`. It should have a very basic definition, where the only thing needed is the API version that needs to be supported. It should override the `get widget()` method to display to the player what version of OpenRCT2 is needed to track the statistic. Priority should be taken to main releases (i.e. v0.4.1 or v0.3.0), and only if there hasn't been an main release should a develop version be suggested (and for simplicity, suggesting the most recent develop version should be fine).

**Comment by Basssiiie** [comment]
Hey I found this issue via the linked OpenRCT2 issue. I'd like to share that there is also a [`context.apiVersion`](https://github.com/OpenRCT2/OpenRCT2/blob/c858b3a8c1917e0624daf2128d5591555c189903/distribution/openrct2.d.ts#L182), which you can use to handle different API versions from within your plugin. You can use it to have different behaviour for older clients, or to show them a message box to tell them to update (like the RideVehicleEditor does [here](https://github.com/Basssiiie/OpenRCT2-RideVehicleEditor/blob/6b2a324850919cd6afc4122b05e46318c052b866/src/main.ts#L11-L18)). 🙂
